package com.playing.lokasee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE.
 */
public class Image {

    private Long id;
    private Integer image_id;
    private Integer order;
    private String path;
    private String type;
    private long event_id;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, Integer image_id, Integer order, String path, String type, long event_id) {
        this.id = id;
        this.image_id = image_id;
        this.order = order;
        this.path = path;
        this.type = type;
        this.event_id = event_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getImage_id() {
        return image_id;
    }

    public void setImage_id(Integer image_id) {
        this.image_id = image_id;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public long getEvent_id() {
        return event_id;
    }

    public void setEvent_id(long event_id) {
        this.event_id = event_id;
    }

}
