package com.playing.lokasee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TICKET.
 */
public class Ticket {

    private Long id;
    private Integer ticket_id;
    private String name;
    private String description;
    private String seatplan;
    private String type;
    private Long price;
    private Integer stock;
    private long schedule_id;

    public Ticket() {
    }

    public Ticket(Long id) {
        this.id = id;
    }

    public Ticket(Long id, Integer ticket_id, String name, String description, String seatplan, String type, Long price, Integer stock, long schedule_id) {
        this.id = id;
        this.ticket_id = ticket_id;
        this.name = name;
        this.description = description;
        this.seatplan = seatplan;
        this.type = type;
        this.price = price;
        this.stock = stock;
        this.schedule_id = schedule_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTicket_id() {
        return ticket_id;
    }

    public void setTicket_id(Integer ticket_id) {
        this.ticket_id = ticket_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSeatplan() {
        return seatplan;
    }

    public void setSeatplan(String seatplan) {
        this.seatplan = seatplan;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getPrice() {
        return price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public long getSchedule_id() {
        return schedule_id;
    }

    public void setSchedule_id(long schedule_id) {
        this.schedule_id = schedule_id;
    }

}
